### ISSUE TITLE
Widget shouldn't require a last name

### ISSUE THREAD

**Issue by Afroholic78** [saasquatch/squatch-js#10]
We're using the Widget to allow our users to send referrals but we're finding that if a last name isn't provided we're unable to show the user's sent invites.
In the case where a last name isn't provided we're still able to identify them in the Saasquatch dashboard but they can't see the referrals they've sent out.
Since users may not have a last name or choose to not put one in, it will be a confusing experience on our end. 

When a user doesn't have a last name:
<img width="526" alt="Screen Shot 2019-12-13 at 2 26 46 PM" src="https://user-images.githubusercontent.com/5957488/70925707-f2868f80-1fe8-11ea-9d5a-c349f9c4c0ab.png">

When the same user has a last name:
<img width="516" alt="Screen Shot 2019-12-16 at 9 46 05 AM" src="https://user-images.githubusercontent.com/5957488/70925732-fadeca80-1fe8-11ea-826f-ed3bf09fa55f.png">

**Comment by jericmason** [comment]
Hi Mickael, thanks for reporting this; I talked to Jon and it sounds like this happened because of a missing program identifier in the request. The system currently falls back to a legacy default widget when the program identifier is left out. We have something in the pipeline to improve this experience. I'm closing this issue for now, but feel free to reopen in you run into further issues.
